project_id: 488923
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: ./
preserve_hierarchy: true
files:
  - source: '/docs/**/*.*'
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/%original_path%/%original_file_name%
    ignore:
      - CNAME
      - '/**/.git**'
      - '/**/*.png'
      - '/**/*.gif'
      - '/**/*.jpg'