files:
  - source: /docs
    ignore:
      - CNAME
      - .git**
      - '**.png'
      - '**.gif'
      - '**.jpg'
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/%original_path%/%original_file_name%
