site_name: Kedôm
dev_addr: 'localhost:8003'
docs_dir: docs/public
theme:
  name: material
  logo: assets/world_icon.png
  favicon: assets/world_fav.png
  palette:
    scheme: youtube
  features:
    - navigation.instant
    - header.autohide
      #- navigation.tabs
      #- navigation.sections
plugins:
  - search: 
      lang:
        - en
        - ru
  - exclude:
      glob:
        - include/*

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - fancyboxmd
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      # clickable_checkbox: true
  - toc:
      slugify: !!python/name:slugify.slugify #pip install python-slugify
extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
google_analytics:
  - G-HX1RPQ876D
  - auto
copyright: Copyright &copy; 2021 OwlbearDM
extra:
  social:
    - icon: fontawesome/solid/dragon
      link: https://owlbeardm.com/
      name: OwlbearDm.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OwlbearDm
      name: OwlbearDm on Twitter